limit_req_zone $binary_remote_addr zone=api_ip:10m rate=100r/s;
limit_req_zone $binary_remote_addr zone=order_ip:10m rate=10r/s;

server {
    listen 8080;
    server_name _;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $public_api_upstream http://public-api:8000;
    set $admin_api_upstream http://admin-api:8001;

    location /health {
        proxy_pass $public_api_upstream/v1/health/live;
    }

    location /v1/admin/ {
        limit_req zone=api_ip burst=200 nodelay;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $admin_api_upstream;
    }

    location /v1/orders {
        limit_req zone=order_ip burst=50 nodelay;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $public_api_upstream;
    }

    location /v1/ {
        limit_req zone=api_ip burst=200 nodelay;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $public_api_upstream;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass $public_api_upstream;
    }
}
